// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbx

var TableNames = struct {
	Orders   string
	Products string
	Receipts string
	Users    string
}{
	Orders:   "orders",
	Products: "products",
	Receipts: "receipts",
	Users:    "users",
}
