// Code generated by SQLBoiler 3.6.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package db

import "testing"

// This test suite runs each operation test in parallel.
// Example, if your database has 3 tables, the suite will run:
// table1, table2 and table3 Delete in parallel
// table1, table2 and table3 Insert in parallel, and so forth.
// It does NOT run each operation group in parallel.
// Separating the tests thusly grants avoidance of Postgres deadlocks.
func TestParent(t *testing.T) {
	t.Run("Orders", testOrders)
	t.Run("Products", testProducts)
	t.Run("Receipts", testReceipts)
	t.Run("Users", testUsers)
}

func TestDelete(t *testing.T) {
	t.Run("Orders", testOrdersDelete)
	t.Run("Products", testProductsDelete)
	t.Run("Receipts", testReceiptsDelete)
	t.Run("Users", testUsersDelete)
}

func TestQueryDeleteAll(t *testing.T) {
	t.Run("Orders", testOrdersQueryDeleteAll)
	t.Run("Products", testProductsQueryDeleteAll)
	t.Run("Receipts", testReceiptsQueryDeleteAll)
	t.Run("Users", testUsersQueryDeleteAll)
}

func TestSliceDeleteAll(t *testing.T) {
	t.Run("Orders", testOrdersSliceDeleteAll)
	t.Run("Products", testProductsSliceDeleteAll)
	t.Run("Receipts", testReceiptsSliceDeleteAll)
	t.Run("Users", testUsersSliceDeleteAll)
}

func TestExists(t *testing.T) {
	t.Run("Orders", testOrdersExists)
	t.Run("Products", testProductsExists)
	t.Run("Receipts", testReceiptsExists)
	t.Run("Users", testUsersExists)
}

func TestFind(t *testing.T) {
	t.Run("Orders", testOrdersFind)
	t.Run("Products", testProductsFind)
	t.Run("Receipts", testReceiptsFind)
	t.Run("Users", testUsersFind)
}

func TestBind(t *testing.T) {
	t.Run("Orders", testOrdersBind)
	t.Run("Products", testProductsBind)
	t.Run("Receipts", testReceiptsBind)
	t.Run("Users", testUsersBind)
}

func TestOne(t *testing.T) {
	t.Run("Orders", testOrdersOne)
	t.Run("Products", testProductsOne)
	t.Run("Receipts", testReceiptsOne)
	t.Run("Users", testUsersOne)
}

func TestAll(t *testing.T) {
	t.Run("Orders", testOrdersAll)
	t.Run("Products", testProductsAll)
	t.Run("Receipts", testReceiptsAll)
	t.Run("Users", testUsersAll)
}

func TestCount(t *testing.T) {
	t.Run("Orders", testOrdersCount)
	t.Run("Products", testProductsCount)
	t.Run("Receipts", testReceiptsCount)
	t.Run("Users", testUsersCount)
}

func TestHooks(t *testing.T) {
	t.Run("Orders", testOrdersHooks)
	t.Run("Products", testProductsHooks)
	t.Run("Receipts", testReceiptsHooks)
	t.Run("Users", testUsersHooks)
}

func TestInsert(t *testing.T) {
	t.Run("Orders", testOrdersInsert)
	t.Run("Orders", testOrdersInsertWhitelist)
	t.Run("Products", testProductsInsert)
	t.Run("Products", testProductsInsertWhitelist)
	t.Run("Receipts", testReceiptsInsert)
	t.Run("Receipts", testReceiptsInsertWhitelist)
	t.Run("Users", testUsersInsert)
	t.Run("Users", testUsersInsertWhitelist)
}

// TestToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestToOne(t *testing.T) {
	t.Run("OrderToProductUsingProduct", testOrderToOneProductUsingProduct)
	t.Run("OrderToUserUsingUser", testOrderToOneUserUsingUser)
	t.Run("ReceiptToUserUsingUser", testReceiptToOneUserUsingUser)
}

// TestOneToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOne(t *testing.T) {}

// TestToMany tests cannot be run in parallel
// or deadlocks can occur.
func TestToMany(t *testing.T) {
	t.Run("ProductToOrders", testProductToManyOrders)
	t.Run("UserToOrders", testUserToManyOrders)
	t.Run("UserToReceipts", testUserToManyReceipts)
}

// TestToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneSet(t *testing.T) {
	t.Run("OrderToProductUsingOrders", testOrderToOneSetOpProductUsingProduct)
	t.Run("OrderToUserUsingOrders", testOrderToOneSetOpUserUsingUser)
	t.Run("ReceiptToUserUsingReceipts", testReceiptToOneSetOpUserUsingUser)
}

// TestToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneRemove(t *testing.T) {}

// TestOneToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneSet(t *testing.T) {}

// TestOneToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneRemove(t *testing.T) {}

// TestToManyAdd tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyAdd(t *testing.T) {
	t.Run("ProductToOrders", testProductToManyAddOpOrders)
	t.Run("UserToOrders", testUserToManyAddOpOrders)
	t.Run("UserToReceipts", testUserToManyAddOpReceipts)
}

// TestToManySet tests cannot be run in parallel
// or deadlocks can occur.
func TestToManySet(t *testing.T) {}

// TestToManyRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyRemove(t *testing.T) {}

func TestReload(t *testing.T) {
	t.Run("Orders", testOrdersReload)
	t.Run("Products", testProductsReload)
	t.Run("Receipts", testReceiptsReload)
	t.Run("Users", testUsersReload)
}

func TestReloadAll(t *testing.T) {
	t.Run("Orders", testOrdersReloadAll)
	t.Run("Products", testProductsReloadAll)
	t.Run("Receipts", testReceiptsReloadAll)
	t.Run("Users", testUsersReloadAll)
}

func TestSelect(t *testing.T) {
	t.Run("Orders", testOrdersSelect)
	t.Run("Products", testProductsSelect)
	t.Run("Receipts", testReceiptsSelect)
	t.Run("Users", testUsersSelect)
}

func TestUpdate(t *testing.T) {
	t.Run("Orders", testOrdersUpdate)
	t.Run("Products", testProductsUpdate)
	t.Run("Receipts", testReceiptsUpdate)
	t.Run("Users", testUsersUpdate)
}

func TestSliceUpdateAll(t *testing.T) {
	t.Run("Orders", testOrdersSliceUpdateAll)
	t.Run("Products", testProductsSliceUpdateAll)
	t.Run("Receipts", testReceiptsSliceUpdateAll)
	t.Run("Users", testUsersSliceUpdateAll)
}
