name: Build Android App
on: [push, pull_request]
jobs:
  build-android:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["13", "10"]
    name: Node ${{ matrix.node }} sample
    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://registry.npmjs.org/

      - name: Install npm dependencies
        working-directory: ./client
        run: npm install

      - name: Build
        working-directory: ./client
        run: cd android && ./gradlew assembleRelease
