name: Build Android App
on: [push, pull_request]
jobs:
  build-android:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["13", "10"]
    name: Node ${{ matrix.node }} sample
    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://registry.npmjs.org/

      - name: Cache NPM dependencies
        uses: actions/cache@v1
        with:
          path: client/node_modules
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-

      - name: Install yarn dependencies
        working-directory: ./client
        run: yarn --frozen-lockfile

      - name: Build
        working-directory: ./client
        run: | 
          mkdir config
          echo "export const BACKEND_URL = 'https://aumo-api.deliriumproducts.me/api/v1'" > ./config/index.js
          cd android 
          ./gradlew bundleRelease
