name: Build Android App
on: [push, pull_request]
jobs:
  build-android:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['13', '10']
    name: Node ${{ matrix.node }} sample
    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
          registry-url: https://registry.npmjs.org/

      - name: Cache NPM dependencies
        uses: actions/cache@v1
        with:
          path: client/node_modules
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-

      - name: Install yarn dependencies
        working-directory: ./client
        run: yarn --frozen-lockfile

      - name: Add keystore
        env:
          KEY_STORE: ${{ secrets.KEY_STORE }}
        shell: bash
        run: 'echo $KEY_STORE | base64 --decode > ./client/android/keystores/aumo.keystore'

      - name: Add release properties
        env:
          RELEASE_PROPERTIES: ${{ secrets.RELEASE_PROPERTIES }}
        shell: bash
        run: 'echo $RELEASE_PROPERTIES > ./client/android/keystores/release.keystore.properties'

      - name: Debug
        run: 'cat ./client/android/keystores/release.keystore.properties'

      - name: Build
        working-directory: ./client/android
        run: |
          echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
          ./gradlew assembleRelease
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: aumo.apk
          path: ./client/android/app/build/outputs/apk/release/app-release.apk
