name: ci
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Install golangci-lint
        run: |
          go get github.com/golangci/golangci-lint/cmd/golangci-lint
      - name: Run linters
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin   
          golangci-lint -E bodyclose,misspell,gocyclo,gofmt,golint,unconvert,goimports,depguard,gocritic,interfacer run
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        if: success()
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Create MySQL database
        run: echo 'CREATE DATABASE aumo_test;' | mysql --user=root --password=root
      - name: Setup Redis
        uses: supercharge/redis-github-action@1.1.0
        with:
          redis-version: 5
      - name: Run tests
        env:
          MYSQL_USER: root
          MYSQL_PASSWORD: root
          MYSQL_HOST: localhost
          MYSQL_DATABASE: aumo_test
          REDIS_URL=redis://localhost
        run: go test -v -covermode=atomic -race  ./...
  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x
      - name: Checkout code
        uses: actions/checkout@v1
      - name: build
        run: |
          export GO111MODULE=on
          GOOS=windows GOARCH=amd64 go build -o bin/ci-test-windows-amd64.exe
          GOOS=linux   GOARCH=amd64 go build -o bin/ci-test-linux-amd64
          GOOS=darwin  GOARCH=amd64 go build -o bin/ci-test-macos-amd64
      - name: upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: binaries
          path: bin/
