name: build-and-deploy
on:
  push:
  branches:
    - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: [lint, test, build]
    env:
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
    steps:
      - name: POST webhook
      run: curl --request POST "${WEBHOOK_URL}"
